name: GMGG
favicon: null
layout_spectrum: 0.8457979562226683
typography_spectrum: 0.7739894974511117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.29224837897345424
  lightness: 0.23346820753067732
  saturation: 0.8076065464410931
  rhythmicContrast: 0.41604263754561543
purpose: []
