name: GMGG
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a22b53'
    - '#ad5d14'
    - '#31351c'
    - '#8da44c'
    - '#0c0c0c'
  brandStrength: 0.1875
  lightness: 0.23346820753067732
  saturation: 0.8076065464410931
  rhythmicContrast: 0.41604263754561543
purpose: []
